source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

target 'RXUMDemo2' do
  pod 'Toast'

# 集成新浪微博
pod 'UMengUShare/Social/Sina'
# 集成微信
pod 'UMengUShare/Social/WeChat'
# 集成QQ
pod 'UMengUShare/Social/QQ'
# 集成豆瓣
pod 'UMengUShare/Social/Douban'
# 集成人人
pod 'UMengUShare/Social/Renren'
# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMengUShare/UI'
end
